spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3307/modular1
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: admin1024
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000ms

server:
  port: 8080

jwt:
  access-expire-ms: 200000
  secret: "asdfasfaslkfjvkasjflskjvfkdsjvfklsjavlksjavslkj vflskj vfklsj vfsdjkvfshnaivueiup"
  issuer: "hello"
kis:
  admin:
    appkey: ${KIS_ADMIN_APPKEY}
    appSecret: ${KIS_ADMIN_APPSECRET}
