spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3307/modular1
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: admin1024
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000ms

server:
  port: 8080

jwt:
  access-expire-ms: 200000
  secret: "asdfasfaslkfjvkasjflskjvfkdsjvfklsjavlksjavslkj vflskj vfklsj vfsdjkvfshnaivueiup"
  issuer: "hello"
kis:
  admin:
    appkey: PS2NHUhlEcq2kctpGPPPuqkkDSOpAWPJV4gI
    appSecret: MjbbLWxrlwhTn7+K2FnlWoVsmxMv/APKHmQ0Kr8sQvHIAGZ7UNrN+LOVrY8plPj6aCgdN8xIY1YTFyF+ALo0DsWu1qA+DVHUeL8lmOPW996jB/Fmnxm2DV+s29d0d1nSLLn+cCTDd6uGqEAMOSDe8d57MRDB/dY3h7K6SR5Gl2mUHDYaGBA=

    

