spring:
  config:
    import:
      - optional:classpath:application-common.yml
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  application:
    name: trading-service

server:
  port: 8082

module:
  strategy-service:
    url: http://localhost:8081
