spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3307/modular1
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: admin1024
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  data:
    mongodb:
      uri: mongodb+srv://pda_user:<password는 우리 프로젝트 공유 파일 참고>@modular1.l9vuztw.mongodb.net/?retryWrites=true&w=majority&appName=modular1
      database: pda-db
  sql:
    init:
      mode: always

server:
  port: 8080
