spring:
  config:
    import:
      - optional:classpath:application-common.yml
  application:
    name: strategy-service
  data:
    mongodb:
      uri: mongodb+srv://pda_user:pda_user1234@modular1.l9vuztw.mongodb.net/?retryWrites=true&w=majority&appName=modular1
      database: pda-db
server:
  port: 8081
openai:
  api-key: ${OPENAI_API_KEY:}
  model: gpt-4o-mini
  temperature: 0.4