spring:
  config:
    import:
      - optional:classpath:application-common.yml
  application:
    name: strategy-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: pda-db
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.mariadb.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MariaDBDialect}
server:
  port: 8081

# Kubernetes 설정
kubernetes:
  namespace: backend
  ecr-image: 618221165332.dkr.ecr.ap-northeast-2.amazonaws.com/strategy-runner:latest
  image-pull-secret: ecr-secret

# Kafka 설정
kafka:
  bootstrap-servers: my-cluster-kafka-bootstrap.kafka:9092

# 서비스 URL 설정
trading-service:
  url: http://trading-service.backend:8082

strategy-service:
  url: http://strategy-service.backend:8081

openai:
  api-key: ${OPENAI_API_KEY:}
  model: gpt-4o-mini
  temperature: 0.4
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    db:
      enabled: false
    defaults:
      enabled: false
